name: Deploy Lambda to S3

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci

    - name: Build ZIP file
      run: zip -r lambda_exercise.zip ./

    - name: Upload ZIP file to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --delete  --exclude '*' --include 'lambda_exercise.zip'
      env:
        AWS_REGION: ap-southeast-1
        AWS_S3_BUCKET: lambda-function-store-techops
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
